const entities = [
  {en:'Button', cn:'按钮', cat:'Controls', def:'触发一个明确动作的交互控件。', type:'ACTION', preview:'button', use:'保存、提交、删除、打开或确认一个动作。', states:['Default 默认','Hover 悬停','Focus 聚焦','Disabled 禁用','Loading 加载']},
  {en:'Text field', cn:'文本输入框', cat:'Forms', def:'让用户输入一行文字的字段。', type:'INPUT', preview:'input', use:'名称、关键词、短文本等单行输入。', states:['Empty 空值','Filled 已填写','Focus 聚焦','Invalid 无效','Disabled 禁用']},
  {en:'Toggle', cn:'切换开关', cat:'Controls', def:'在两个互斥状态之间快速切换。', type:'STATE', preview:'toggle', use:'开启通知、深色模式或某项设置。', states:['Off 关闭','On 开启','Focus 聚焦','Disabled 禁用']},
  {en:'Card', cn:'卡片', cat:'Structure', def:'独立承载一组相关内容的容器。', type:'CONTAINER', preview:'card', use:'商品、文章、用户、统计信息的独立展示单元。', states:['Rest 静止','Hover 悬停','Selected 已选','Loading 加载']},
  {en:'Tabs', cn:'标签页', cat:'Navigation', def:'在同一区域的多个内容面板之间切换。', type:'NAVIGATION', preview:'tabs', use:'设置页、详情页或同级内容分类。', states:['Active 当前','Inactive 未选','Focus 聚焦','Disabled 禁用']},
  {en:'Alert', cn:'警告提示', cat:'Feedback', def:'页面中需要用户注意的一条重要消息。', type:'FEEDBACK', preview:'alert', use:'错误、警告、成功或一般信息的持续提示。', states:['Info 信息','Success 成功','Warning 警告','Error 错误']},
  {en:'Progress bar', cn:'进度条', cat:'Feedback', def:'表示任务已经完成多少的视觉指示器。', type:'STATUS', preview:'progress', use:'上传、安装、导出等有明确进度的任务。', states:['0% 未开始','In progress 进行中','Complete 已完成','Error 失败']},
  {en:'Modal', cn:'模态框', cat:'Overlays', def:'覆盖页面并要求用户先处理的弹层。', type:'OVERLAY', preview:'modal', use:'确认危险操作、编辑内容或完成短流程。', states:['Closed 关闭','Open 打开','Loading 加载','Error 错误']},
  {en:'Tooltip', cn:'工具提示', cat:'Overlays', def:'在悬停或聚焦时补充说明一个元素。', type:'OVERLAY', preview:'tooltip', use:'解释图标、缩写或不明显的控件含义。', states:['Hidden 隐藏','Visible 显示','Focus 聚焦']},
  {en:'Skeleton', cn:'骨架屏', cat:'Feedback', def:'内容加载期间的结构化占位图形。', type:'LOADING', preview:'skeleton', use:'让用户提前感知页面结构，等待真实内容。', states:['Loading 加载','Loaded 已加载','Error 失败']},
  {en:'Breadcrumb', cn:'面包屑导航', cat:'Navigation', def:'展示当前页面在层级路径中的位置。', type:'NAVIGATION', preview:'breadcrumb', use:'文档、设置、商品分类等多层级页面。', states:['Current 当前','Linked 可跳转']},
  {en:'Empty state', cn:'空状态', cat:'Feedback', def:'当一个区域暂时没有内容时提供的引导。', type:'STATE', preview:'empty', use:'首次使用、搜索无结果或列表被清空时。', states:['No data 无数据','No result 无结果','Action available 可操作']}
];
const categories = ['All / 全部', ...new Set(entities.map(e => e.cat))];
let selected = 'All / 全部';
const nav = document.querySelector('#category-nav'); const filters = document.querySelector('#filter-row'); const cards = document.querySelector('#cards'); const empty = document.querySelector('#empty-state');
const preview = e => ({button:'<button data-action="save">保存 Save</button>', input:'<input data-action="input" aria-label="示例输入框" placeholder="输入内容…">', toggle:'<button class="switch" data-action="toggle" aria-pressed="false" aria-label="切换开关"><i></i></button>', card:'<div class="pill">CARD / 内容</div>', tabs:'<div class="tabs"><button data-action="tab" class="active">概览 Overview</button><button data-action="tab">详情 Details</button></div>', alert:'<button class="pill" data-action="alert">✓ 已保存 Saved</button>', progress:'<button class="bar" data-action="progress" aria-label="增加进度"><i></i></button>', modal:'<button class="pill" data-action="modal">OPEN / 打开</button>', tooltip:'<button class="pill" data-action="tooltip">ⓘ Hover me</button>', skeleton:'<div class="skeleton"></div>', breadcrumb:'<div class="pill">Home / Docs / Page</div>', empty:'<button class="pill" data-action="empty">∅ 暂无内容</button>'}[e.preview]);
function renderNav(){ nav.innerHTML = categories.map(c => `<button class="${c===selected?'active':''}" data-cat="${c}">${c}</button>`).join(''); filters.innerHTML = categories.slice(1).map(c => `<button class="tag ${c===selected?'active':''}" data-cat="${c}">${c}</button>`).join(''); document.querySelectorAll('[data-cat]').forEach(b => b.onclick=()=>{selected=b.dataset.cat; renderNav(); renderCards();}); }
function renderCards(){ const term=document.querySelector('#search-input').value.toLowerCase(); const list=entities.filter(e=>(selected==='All / 全部'||e.cat===selected)&&[e.en,e.cn,e.cat,e.def,e.use].join(' ').toLowerCase().includes(term)); cards.innerHTML=list.map((e,i)=>`<article class="entity-card" tabindex="0" data-index="${entities.indexOf(e)}"><div class="card-top"><span class="meta">${String(i+1).padStart(2,'0')} / ${e.type}</span><span class="meta">${e.cat}</span></div><h3>${e.en}</h3><div class="cn">${e.cn}</div><div class="preview">${preview(e)}</div><p class="definition">${e.def}</p></article>`).join(''); empty.hidden=list.length>0; document.querySelectorAll('.entity-card').forEach(c=>{c.onclick=()=>openDialog(entities[c.dataset.index]); c.onkeydown=ev=>{if(ev.target===c&&(ev.key==='Enter'||ev.key===' ')){ev.preventDefault();openDialog(entities[c.dataset.index]);}}}); document.querySelectorAll('[data-action]').forEach(control=>{control.onclick=ev=>{ev.stopPropagation(); const action=control.dataset.action; if(action==='save')control.textContent='✓ 已保存 Saved'; if(action==='toggle'){const on=control.getAttribute('aria-pressed')==='true'; control.setAttribute('aria-pressed',String(!on)); control.classList.toggle('on',!on);} if(action==='tab'){control.closest('.tabs').querySelectorAll('button').forEach(tab=>tab.classList.remove('active')); control.classList.add('active');} if(action==='progress'){const bar=control.querySelector('i'); const current=parseInt(control.dataset.progress||'63',10); const next=current>=100?0:current+10; control.dataset.progress=next; bar.style.width=`${next}%`;} if(action==='alert'){control.textContent='× 已关闭 Closed'; control.disabled=true;} if(action==='modal')openDialog(entities[c.dataset.index]); if(action==='tooltip')control.textContent='说明已显示 Shown';};}); }
function openDialog(e){ document.querySelector('#dialog-content').innerHTML=`<div class="meta">${e.type} · ${e.cat}</div><h2 class="dialog-title">${e.en}</h2><div class="dialog-cn">${e.cn}</div><p>${e.def}</p><div class="dialog-block"><h4>Common use / 常见用途</h4><p>${e.use}</p></div><div class="dialog-block"><h4>States / 状态</h4><div class="states">${e.states.map(s=>`<span class="state">${s}</span>`).join('')}</div></div>`; document.querySelector('#entity-dialog').showModal(); }
document.querySelector('#search-input').oninput=renderCards; document.querySelector('.dialog-close').onclick=()=>document.querySelector('#entity-dialog').close(); document.querySelector('#entity-dialog').onclick=e=>{if(e.target.id==='entity-dialog')e.target.close();}; document.querySelector('.contrast-toggle').onclick=e=>{const high=document.body.classList.toggle('high-contrast'); e.currentTarget.setAttribute('aria-pressed',high); e.currentTarget.innerHTML=high?'亮度 <span>●</span>':'亮度 <span>○</span>';}; renderNav(); renderCards();
